src/Entity/Video.php
<?php

namespace App\Entity;

use App\Repository\VideoRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=VideoRepository::class)
 *
 * @ORM\HasLifecycleCallbacks()
 *
 */
class Video
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     *
     * @Assert\NotBlank(
     *     message="Merci de renseigner votre Nom.",
     *     groups={"newVideo"}
     *     )
     *
     * @Assert\NotBlank(
     *     message="Merci de renseigner votre Nom.",
     *     )
     */
    private $Nom;

    /**
     * @ORM\Column(type="text", length=255)
     *
     * @Assert\NotBlank(
     *     message="Merci de renseigner un Synopsis.",
     *     groups={"newVideo"}
     *     )
     *
     * @Assert\NotBlank(
     *     message="Merci de renseigner un Synopsis.",
     *     )
     */
    private $Synopsis;

    /**
     * @ORM\Column(type="string", length=255)
     *
     * @Assert\NotBlank(
     *     message="Merci de renseigner un type série ou film.",
     *     groups={"newVideo"}
     *     )
     *
     * @Assert\NotBlank(
     *     message="Merci de renseigner un type série ou film.",
     *     )
     *
     *
     */
    private $Type;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    /**
     * @ORM\PrePersist()
     * @ORM\PreUpdate()
     */
    public function prePersist()
    {
        if (empty($this->getCreatedAt())) {
            $this->setCreatedAt(new \DateTime());
        }
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(string $Nom): self
    {
        $this->Nom = $Nom;

        return $this;
    }

    public function getSynopsis(): ?string
    {
        return $this->Synopsis;
    }

    public function setSynopsis(string $Synopsis): self
    {
        $this->Synopsis = $Synopsis;

        return $this;
    }

    public function getType(): ?string
    {
        return $this->Type;
    }

    public function setType(string $Type): self
    {
        $this->Type = $Type;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }
}

src/Form/VideoType.php
<?php

namespace App\Form;

use App\Entity\Video;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class VideoType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('Nom', TextType::class)
            ->add('Synopsis', TextType::class)
            ->add('Type', TextType::class)
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Video::class,
        ]);
    }
}

src/Controller/VideoController.php
<?php

namespace App\Controller;

use App\Entity\Video;
use App\Form\VideoType;
use App\Repository\VideoRepository;
use App\Service\SerializerService;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Validator\Validator\ValidatorInterface;

class VideoController extends AbstractController
{
    private SerializerService $serializerService;
    private EntityManagerInterface $entityManager;

    public function __construct(SerializerService $serializerService, EntityManagerInterface $em)
    {
        $this->serializerService = $serializerService;
        $this->entityManager     = $em;
    }

    /**
     * @Route("/create", name="add_video_api")
     */
    public function createApiVideo(Request $request, ValidatorInterface $validator): JsonResponse
    {
        $datas = json_decode($request->getContent(), true);

        if ($datas !== null && $datas !== '') {

            $video = new Video();

            $form = $this->createForm(VideoType::class, $video);

            $form->submit($datas);

            $validate = $validator->validate($video, null, 'newVideo');

            if (count($validate) !== 0) {
                foreach ($validate as $error) {
                    return new JsonResponse($error->getMessage(), Response::HTTP_BAD_REQUEST);
                }
            }

            $this->entityManager->persist($video);

            $this->entityManager->flush();

            return new JsonResponse("Your video has been added successfully", Response::HTTP_CREATED);

        } else {
            return new JsonResponse("Something went wrong, please send available datas", Response::HTTP_BAD_REQUEST);
        }
    }

    /**
     * @Route("/getall", name="get_all_video_api")
     */
    public function getAllVideoApi(VideoRepository $videoRepository): JsonResponse
    {
        return JsonResponse::fromJsonString($this->serializerService->SimpleSerializer($videoRepository->findAll(),'json'),Response::HTTP_OK);
    }

    /**
     * @Route("/get/{id_item}", name="get_one_video_api")
     */
    public function getOneVideoApi($id_item, VideoRepository $videoRepository): JsonResponse
    {
        $video = $videoRepository->findOneBy(['id' => $id_item]);

        if (!empty($video)) {
        return JsonResponse::fromJsonString($this->serializerService->SimpleSerializer($videoRepository->findOneBy(['id' => $id_item]),'json'),Response::HTTP_OK);
        } else {
            return new JsonResponse("We can't  find this video", Response::HTTP_BAD_REQUEST);
        }
    }
}

templates/video/addVideo.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ajout vidéo{% endblock %}

{% block body %}
    <div class="container">
        <h1 class="text-center my-5">Ajout d'une vidéo</h1>
        {{ form_start(form) }}
        <div class="row">
            <div class="col">
                <div class="alert alert-light">
                    <h2 class="alert-heading">Ajout de la vidéo</h2>
                    {{ form_row(form.Nom) }}
                </div>
                <div class="alert alert-light">
                    {{ form_row(form.Synopsis) }}
                </div>
                <div class="alert alert-light">
                    {{ form_row(form.Type) }}
                    <div class="containerSubmitRegisterbtn mt-5">
                        <button type="submit" class="btn btn-success submitRegisterBtn"><i class="fas fa-check"></i>
                            Ajout de la vidéo
                        </button>
                    </div>
                </div>
            </div>
            {{ form_end(form) }}
        </div>
    </div>
{% endblock %}

templates/video/video.html.twig
{% extends 'base.html.twig' %}

{% block title %}Vidéo{% endblock %}

{% block body %}
    <div class="container">
        <div class="card">
            <div class="card-header">
                <img class="card-img-top" width="250" height="600" src="https://picsum.photos/50" alt="picsum image">
            </div>
            <div class="card-body">
                <h5 class="card-title">{{ video.nom }}</h5>
                <h4>{{ video.type }}</h4>
                <p class="card-text">{{ video.synopsis }}</p>
            </div>
        </div>
    </div>
{% endblock %}